/**
 * ANIME DATABASE - 50 ENTRIES
 * Status: Sinopsis Lengkap & Kode Stabil
 */

const animeDatabase = [
  {
    id: 1,
    title: "Jujutsu Kaisen",
    day: "Kamis",
    time: "23:00",
    genre: ["Action", "Supernatural"],
    img: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
    desc: "Yuji Itadori adalah siswa SMA dengan kekuatan fisik luar biasa yang secara tidak sengaja memakan jari terkutuk milik Ryomen Sukuna. Demi melindungi orang lain dan mencari semua jari Sukuna, ia bergabung dengan SMA Jujutsu Tokyo untuk belajar cara membasmi kutukan.",
    studio: "MAPPA",
    episodes: [{ n: 1, ytId: "yv5-Z6Xv828", title: "Ryomen Sukuna" }],
    sources: ["Ani-One Asia"]
  },
  {
    id: 2,
    title: "Spy x Family",
    day: "Sabtu",
    time: "22:00",
    genre: ["Comedy", "Action"],
    img: "https://cdn.myanimelist.net/images/anime/1441/122795.jpg",
    desc: "Seorang agen mata-mata bernama Twilight harus membentuk keluarga palsu demi misi perdamaian. Namun, ia tidak sadar bahwa istrinya adalah pembunuh bayaran dan anaknya adalah seorang telepatis yang bisa membaca pikiran.",
    studio: "Wit Studio & CloverWorks",
    episodes: [{ n: 1, ytId: "eX2qF9kI5pU", title: "Operation Strix" }],
    sources: ["Muse Indonesia"]
  },
  {
    id: 3,
    title: "Blue Lock",
    day: "Minggu",
    time: "00:00",
    genre: ["Sports", "Drama"],
    img: "https://cdn.myanimelist.net/images/anime/1258/126920.jpg",
    desc: "Setelah kegagalan Jepang di Piala Dunia, sebuah fasilitas pelatihan bernama Blue Lock didirikan untuk menciptakan striker paling egois dan hebat di dunia melalui kompetisi eliminasi yang kejam di antara 300 pemain muda.",
    studio: "Eight Bit",
    episodes: [{ n: 1, ytId: "w_6A97G9X7A", title: "Dream" }],
    sources: ["Ani-One Asia"]
  },
  {
    id: 4,
    title: "Chainsaw Man",
    day: "Rabu",
    time: "23:00",
    genre: ["Action", "Gore"],
    img: "https://cdn.myanimelist.net/images/anime/1806/126216.jpg",
    desc: "Denji hidup dalam kemiskinan ekstrem bersama Pochita, iblis gergaji. Setelah dikhianati dan dibunuh, ia bangkit kembali dengan jantung Pochita, menjadi 'Chainsaw Man' yang liar dan bergabung dengan Pemburu Iblis Keamanan Publik.",
    studio: "MAPPA",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Dog & Chainsaw" }],
    sources: ["Ani-One Asia"]
  },
  {
    id: 5,
    title: "Oregairu",
    day: "Jumat",
    time: "00:00",
    genre: ["Romance", "Drama"],
    img: "https://cdn.myanimelist.net/images/anime/7/49631.jpg",
    desc: "Hachiman Hikigaya, seorang pemuda sinis yang membenci hubungan sosial, dipaksa bergabung dengan Klub Relawan. Di sana ia bertemu Yukino dan Yui, di mana mereka harus menyelesaikan masalah siswa lain sambil menghadapi konflik batin mereka sendiri.",
    studio: "Brain's Base",
    episodes: [{ n: 1, ytId: "A2WvXpW265A", title: "The Beginning" }],
    sources: ["Muse Indonesia"]
  },
  {
    id: 6,
    title: "Frieren: Beyond Journey's End",
    day: "Jumat",
    time: "23:00",
    genre: ["Adventure", "Fantasy"],
    img: "https://cdn.myanimelist.net/images/anime/1015/138006.jpg",
    desc: "Setelah kelompok pahlawan mengalahkan Raja Iblis, Elf penyihir Frieren memulai perjalanan panjang untuk memahami manusia. Sebagai makhluk abadi, ia harus belajar menghadapi kehilangan saat teman-temannya mulai menua dan mati.",
    studio: "Madhouse",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "The Journey Begins" }],
    sources: ["Muse Indonesia"]
  },
  {
    id: 7,
    title: "The Eminence in Shadow",
    day: "Rabu",
    time: "22:00",
    genre: ["Action", "Fantasy"],
    img: "https://cdn.myanimelist.net/images/anime/1623/126939.jpg",
    desc: "Cid Kagenou terobsesi menjadi dalang di balik layar. Setelah bereinkarnasi, ia mendirikan organisasi Shadow Garden untuk melawan sekte jahat. Masalahnya, ia mengira sekte itu fiksi, padahal ancaman itu nyata.",
    studio: "Nexus",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Shadow" }],
    sources: ["Bstation"]
  },
  {
    id: 8,
    title: "Horimiya",
    day: "Minggu",
    time: "21:00",
    genre: ["Romance", "Slice of Life"],
    img: "https://cdn.myanimelist.net/images/anime/1103/112387.jpg",
    desc: "Kisah cinta manis antara Hori, gadis populer yang sebenarnya ibu rumah tangga di rumah, dan Miyamura, cowok suram yang ternyata memiliki banyak tindik dan tato. Mereka saling berbagi sisi lain yang tidak diketahui teman sekolahnya.",
    studio: "CloverWorks",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Small Happenings" }],
    sources: ["Bstation"]
  },
  {
    id: 9,
    title: "Mushoku Tensei",
    day: "Minggu",
    time: "22:00",
    genre: ["Isekai", "Adventure"],
    img: "https://cdn.myanimelist.net/images/anime/1530/112615.jpg",
    desc: "Seorang pengangguran yang payah bereinkarnasi ke dunia sihir sebagai bayi bernama Rudeus. Berbekal ingatan masa lalu, ia bertekad menjalani hidup barunya dengan serius dan menjadi penyihir hebat tanpa penyesalan.",
    studio: "Studio Bind",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "New Life" }],
    sources: ["Muse Indonesia"]
  },
  {
    id: 10,
    title: "Classroom of the Elite",
    day: "Rabu",
    time: "21:00",
    genre: ["Psychological", "School"],
    img: "https://cdn.myanimelist.net/images/anime/1015/138006.jpg",
    desc: "Di SMA Koudo Ikusei yang sangat kompetitif, nilai dan poin menentukan strata sosial. Kiyotaka Ayanokouji, seorang jenius yang menyembunyikan kemampuannya, harus memanipulasi situasi dari balik layar untuk membantu Kelas D naik tingkat.",
    studio: "Lerche",
    episodes: [{ n: 1, ytId: "8jW8uA_qFjM", title: "What is Evil?" }],
    sources: ["Muse Indonesia"]
  },
  {
    id: 11,
    title: "Demon Slayer: Kimetsu no Yaiba",
    day: "Minggu",
    time: "22:30",
    genre: ["Action", "Historical"],
    img: "https://cdn.myanimelist.net/images/anime/1286/99889.jpg",
    desc: "Tanjiro Kamado menjadi pembasmi iblis setelah keluarganya dibantai dan adiknya, Nezuko, berubah menjadi iblis. Ia berjuang mencari cara untuk mengembalikan kemanusiaan adiknya dan membalas dendam pada Muzan.",
    studio: "ufotable",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Cruelty" }],
    sources: ["Bstation"]
  },
  {
    id: 12,
    title: "Tokyo Revengers",
    day: "Minggu",
    time: "01:00",
    genre: ["Action", "Drama"],
    img: "https://cdn.myanimelist.net/images/anime/1452/115527.jpg",
    desc: "Takemichi Hanagaki melakukan perjalanan waktu kembali ke masa SMP untuk menyelamatkan pacarnya dari kematian akibat ulah geng Tokyo Manji. Ia harus mendaki hierarki geng tersebut untuk mengubah masa depan.",
    studio: "LIDENFILMS",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Reborn" }],
    sources: ["Muse Indonesia"]
  },
  {
    id: 13,
    title: "Bleach: Thousand-Year Blood War",
    day: "Sabtu",
    time: "23:30",
    genre: ["Action", "Fantasy"],
    img: "https://cdn.myanimelist.net/images/anime/1764/126627.jpg",
    desc: "Konflik antara Shinigami dan Quincy pecah kembali saat Yhwach menyerang Soul Society. Ichigo Kurosaki harus melatih kekuatan barunya untuk menghentikan kehancuran seluruh dunia roh.",
    studio: "Pierrot",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "The Blood Warfare" }],
    sources: ["Ani-One Asia"]
  },
  {
    id: 14,
    title: "Steins;Gate",
    day: "Selasa",
    time: "20:00",
    genre: ["Sci-Fi", "Thriller"],
    img: "https://cdn.myanimelist.net/images/anime/15/31355.jpg",
    desc: "Seorang ilmuwan eksentrik, Rintarou Okabe, secara tidak sengaja menciptakan alat yang bisa mengirim pesan ke masa lalu. Namun, tindakannya memicu konsekuensi berbahaya yang mengancam nyawa teman-temannya.",
    studio: "White Fox",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Turning Point" }],
    sources: ["Bstation"]
  },
  {
    id: 15,
    title: "Dr. Stone",
    day: "Kamis",
    time: "22:00",
    genre: ["Sci-Fi", "Adventure"],
    img: "https://cdn.myanimelist.net/images/anime/1613/102179.jpg",
    desc: "Setelah ribuan tahun umat manusia membatu, Senku Ishigami bangun dan bertekad membangun kembali peradaban modern menggunakan kekuatan sains dari titik nol.",
    studio: "TMS Entertainment",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Stone World" }],
    sources: ["Ani-One Asia"]
  },
  {
    id: 16,
    title: "Kaguya-sama: Love is War",
    day: "Sabtu",
    time: "23:00",
    genre: ["Romance", "Comedy"],
    img: "https://cdn.myanimelist.net/images/anime/1295/106551.jpg",
    desc: "Dua jenius, Kaguya dan Miyuki, saling mencintai namun terlalu gengsi untuk mengakuinya. Mereka terjebak dalam perang psikologis lucu untuk membuat pihak lawan menyatakan cinta terlebih dahulu.",
    studio: "A-1 Pictures",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "I Want to Make You Confess" }],
    sources: ["Bstation"]
  },
  {
    id: 17,
    title: "Mashle: Magic and Muscles",
    day: "Sabtu",
    time: "00:00",
    genre: ["Comedy", "Fantasy"],
    img: "https://cdn.myanimelist.net/images/anime/1638/131438.jpg",
    desc: "Di dunia di mana sihir adalah segalanya, Mash Burnedead lahir tanpa sihir sama sekali. Ia harus masuk sekolah sihir dan bertahan hidup hanya mengandalkan kekuatan ototnya yang luar biasa.",
    studio: "A-1 Pictures",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Mash Burnedead" }],
    sources: ["Ani-One Asia"]
  },
  {
    id: 18,
    title: "Blue Box",
    day: "Kamis",
    time: "23:56",
    genre: ["Romance", "Sports"],
    img: "https://cdn.myanimelist.net/images/anime/1900/144933.jpg",
    desc: "Taiki, pemain badminton, mengagumi Chinatsu, bintang basket sekolahnya. Sebuah keadaan tak terduga membuat mereka harus tinggal di bawah atap yang sama, memicu romansa di tengah ambisi olahraga mereka.",
    studio: "Telecom Animation Film",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Chinatsu-senpai" }],
    sources: ["Netflix"]
  },
  {
    id: 19,
    title: "Vinland Saga",
    day: "Senin",
    time: "00:00",
    genre: ["Action", "Seinen"],
    img: "https://cdn.myanimelist.net/images/anime/1500/103005.jpg",
    desc: "Thorfinn mengejar balas dendam terhadap pembunuh ayahnya, Askeladd, di tengah pertempuran berdarah antara bangsa Viking dan Inggris yang sangat brutal.",
    studio: "MAPPA / Wit Studio",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Somewhere Not Here" }],
    sources: ["Netflix"]
  },
  {
    id: 20,
    title: "Bungou Stray Dogs",
    day: "Rabu",
    time: "21:00",
    genre: ["Action", "Supernatural"],
    img: "https://cdn.myanimelist.net/images/anime/1505/135967.jpg",
    desc: "Atsushi Nakajima bergabung dengan Agensi Detektif Bersenjata yang beranggotakan orang-orang berkekuatan supranatural untuk memecahkan berbagai kasus kriminal yang tidak bisa ditangani polisi.",
    studio: "Bones",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Fortune is Unpredictable" }],
    sources: ["Ani-One Asia"]
  },
  {
    id: 21,
    title: "Mob Psycho 100",
    day: "Kamis",
    time: "22:00",
    genre: ["Action", "Comedy"],
    img: "https://cdn.myanimelist.net/images/anime/1918/127878.jpg",
    desc: "Mob adalah remaja dengan kekuatan psikis tak terbatas yang hanya ingin hidup normal. Namun, emosinya yang meledak pada titik 100% seringkali menariknya ke dalam pertempuran supranatural yang dahsyat.",
    studio: "Bones",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Self-Possession" }],
    sources: ["Bstation"]
  },
  {
    id: 22,
    title: "Cyberpunk: Edgerunners",
    day: "Selasa",
    time: "19:00",
    genre: ["Sci-Fi", "Action"],
    img: "https://cdn.myanimelist.net/images/anime/1818/126435.jpg",
    desc: "Di kota masa depan Night City yang korup, seorang anak jalanan mencoba bertahan hidup sebagai 'edgerunner', tentara bayaran kriminal yang menggunakan implan teknologi berbahaya.",
    studio: "Trigger",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Let You Down" }],
    sources: ["Netflix"]
  },
  {
    id: 23,
    title: "Re:Zero - Starting Life in Another World",
    day: "Rabu",
    time: "21:30",
    genre: ["Isekai", "Psychological"],
    img: "https://cdn.myanimelist.net/images/anime/11/79410.jpg",
    desc: "Subaru Natsuki tiba-tiba terpanggil ke dunia lain dan mendapati bahwa ia memiliki kemampuan 'Return by Death'. Ia harus mati berulang kali untuk menyelamatkan orang-orang yang ia cintai dari nasib tragis.",
    studio: "White Fox",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "The End of the Beginning" }],
    sources: ["Muse Indonesia"]
  },
  {
    id: 24,
    title: "That Time I Got Reincarnated as a Slime",
    day: "Selasa",
    time: "23:00",
    genre: ["Isekai", "Fantasy"],
    img: "https://cdn.myanimelist.net/images/anime/1506/117717.jpg",
    desc: "Satoru Mikami bereinkarnasi sebagai monster Slime bernama Rimuru di dunia fantasi. Dengan kemampuan uniknya, ia membangun negara monster yang damai dan berteman dengan berbagai makhluk kuat.",
    studio: "Eight Bit",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Veldora" }],
    sources: ["Muse Indonesia"]
  },
  {
    id: 25,
    title: "Blue Exorcist",
    day: "Minggu",
    time: "00:00",
    genre: ["Action", "Fantasy"],
    img: "https://cdn.myanimelist.net/images/anime/10/75195.jpg",
    desc: "Rin Okumura mengetahui bahwa ia adalah putra Satan. Ia memutuskan untuk menjadi pengusir setan (Exorcist) untuk melawan ayahnya sendiri dan membuktikan kemanusiaannya.",
    studio: "A-1 Pictures",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "The Devil in a Man's Heart" }],
    sources: ["Ani-One Asia"]
  },
  {
    id: 26,
    title: "Fire Force",
    day: "Sabtu",
    time: "01:00",
    genre: ["Action", "Sci-Fi"],
    img: "https://cdn.myanimelist.net/images/anime/1410/101851.jpg",
    desc: "Di dunia di mana manusia bisa terbakar secara spontan dan menjadi Infernals, pasukan pemadam kebakaran khusus bertugas memadamkan mereka sambil mencari tahu misteri di balik fenomena tersebut.",
    studio: "David Production",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Shinra Kusakabe Enlists" }],
    sources: ["Bstation"]
  },
  {
    id: 27,
    title: "Attack on Titan",
    day: "Senin",
    time: "00:00",
    genre: ["Action", "Drama"],
    img: "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
    desc: "Umat manusia hidup di balik dinding raksasa untuk menghindari Titan pemakan manusia. Eren Yeager bersumpah membasmi semua Titan setelah melihat ibunya tewas di depan matanya.",
    studio: "MAPPA / Wit Studio",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "To You, 2000 Years Later" }],
    sources: ["Ani-One Asia"]
  },
  {
    id: 28,
    title: "Overlord",
    day: "Selasa",
    time: "21:00",
    genre: ["Isekai", "Fantasy"],
    img: "https://cdn.myanimelist.net/images/anime/10/73215.jpg",
    desc: "Seorang pemain game terjebak di dalam avatar skeletal-nya, Momonga, saat server game ditutup. Ia memutuskan untuk menaklukkan dunia baru tersebut bersama para pelayan setianya.",
    studio: "Madhouse",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "End and Beginning" }],
    sources: ["Bstation"]
  },
  {
    id: 29,
    title: "86 Eighty-Six",
    day: "Minggu",
    time: "00:00",
    genre: ["Mecha", "Drama"],
    img: "https://cdn.myanimelist.net/images/anime/1987/117507.jpg",
    desc: "Di tengah perang antara Republik San Magnolia dan Kekaisaran Giad, terdapat distrik 86 rahasia tempat para pemuda dipaksa berperang tanpa pengakuan sebagai manusia.",
    studio: "A-1 Pictures",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Undertaker" }],
    sources: ["Bstation"]
  },
  {
    id: 30,
    title: "Your Lie in April",
    day: "Jumat",
    time: "20:00",
    genre: ["Music", "Drama"],
    img: "https://cdn.myanimelist.net/images/anime/3/67177.jpg",
    desc: "Seorang pianis jenius kehilangan kemampuan mendengar nada setelah kematian ibunya. Hidupnya yang suram berubah setelah bertemu pemain biola ceria bernama Kaori Miyazono.",
    studio: "A-1 Pictures",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Monotone" }],
    sources: ["Netflix"]
  },
  {
    id: 31,
    title: "Grand Blue Dreaming",
    day: "Sabtu",
    time: "02:00",
    genre: ["Comedy", "Slice of Life"],
    img: "https://cdn.myanimelist.net/images/anime/1160/94273.jpg",
    desc: "Iori Kitahara memulai kehidupan kampusnya di pinggir pantai. Alih-alih kuliah yang tenang, ia malah terjebak dalam klub selam yang penuh dengan pesta gila dan kegokilan tak terduga.",
    studio: "Zero-G",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Deep Blue" }],
    sources: ["Bstation"]
  },
  {
    id: 32,
    title: "Hell's Paradise",
    day: "Sabtu",
    time: "23:00",
    genre: ["Action", "Supernatural"],
    img: "https://cdn.myanimelist.net/images/anime/1620/134449.jpg",
    desc: "Gabimaru sang ninja pembunuh dijanjikan kebebasan jika ia bisa menemukan ramuan keabadian di sebuah pulau misterius yang dihuni oleh makhluk-makhluk mengerikan.",
    studio: "MAPPA",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "The Death Row" }],
    sources: ["Netflix"]
  },
  {
    id: 33,
    title: "Wind Breaker",
    day: "Kamis",
    time: "23:00",
    genre: ["Action", "Drama"],
    img: "https://cdn.myanimelist.net/images/anime/1460/141708.jpg",
    desc: "Haruka Sakura adalah pemuda yang sering dijauhi karena penampilannya. Ia bergabung dengan SMA Bofurin, sekolah yang dikenal sebagai pelindung kota melalui kekuatan bertarung siswanya.",
    studio: "CloverWorks",
    episodes: [{ n: 1, ytId: "Gq_vD7K6O8w", title: "Sakura and Furin" }],
    sources: ["Bstation"]
  },
  {
    id: 34,
    title: "Food Wars! Shokugeki no Soma",
    day: "Sabtu",
    time: "20:00",
    genre: ["Cooking", "Comedy"],
    img: "https://cdn.myanimelist.net/images/anime/11/74520.jpg",
    desc: "Soma Yukihira masuk ke akademi kuliner elit Totsuki untuk melampaui kemampuan masak ayahnya. Di sana, tantangan masak 'Shokugeki' menentukan nasib setiap siswa.",
    studio: "J.C.Staff",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "The Vast Wasteland" }],
    sources: ["Ani-One Asia"]
  },
  {
    id: 35,
    title: "Assassination Classroom",
    day: "Jumat",
    time: "21:00",
    genre: ["Comedy", "Action"],
    img: "https://cdn.myanimelist.net/images/anime/8/70857.jpg",
    desc: "Sekelompok siswa kelas buangan ditugaskan untuk membunuh guru mereka sendiri, Koro-sensei, sesosok makhluk gurita berkekuatan super yang mengancam akan menghancurkan bumi.",
    studio: "Lerche",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Assassination Time" }],
    sources: ["Bstation"]
  },
  {
    id: 36,
    title: "Gintama",
    day: "Senin",
    time: "18:00",
    genre: ["Comedy", "Action"],
    img: "https://cdn.myanimelist.net/images/anime/10/73274.jpg",
    desc: "Di era Edo yang dijajah alien Amanto, seorang samurai pengangguran bernama Gintoki Sakata menjalankan bisnis serabutan bersama teman-temannya dalam balutan komedi satir dan aksi pedang.",
    studio: "Sunrise",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Odd Jobs Gin-chan" }],
    sources: ["Bstation"]
  },
  {
    id: 37,
    title: "Clannad",
    day: "Sabtu",
    time: "19:00",
    genre: ["Drama", "Romance"],
    img: "https://cdn.myanimelist.net/images/anime/10/11130.jpg",
    desc: "Tomoya Okazaki adalah berandalan sekolah yang hidupnya berubah setelah bertemu dengan Nagisa Furukawa, seorang gadis yang ingin menghidupkan kembali klub teater sekolah.",
    studio: "Kyoto Animation",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "On the Hill Side" }],
    sources: ["Bstation"]
  },
  {
    id: 38,
    title: "Sword Art Online",
    day: "Minggu",
    time: "22:00",
    genre: ["Action", "Adventure"],
    img: "https://cdn.myanimelist.net/images/anime/11/39717.jpg",
    desc: "Ribuan pemain terjebak dalam game VRMMORPG di mana kematian di dalam game berarti kematian di dunia nyata. Kirito harus berjuang menamatkan game tersebut unt    time: "21:00",
    genre: ["Psychological"],
    img: "https://cdn.myanimelist.net/images/anime/1015/138006.jpg",
    desc: "Sekolah elit penuh manipulasi.",
    studio: "Lerche",
    episodes: [{ n: 1, ytId: "8jW8uA_qFjM", title: "Evil" }],
    sources: ["Muse Indonesia"]
  },
  {
    id: 10,
    title: "Frieren",
    day: "Jumat",
    time: "23:00",
    genre: ["Adventure", "Fantasy"],
    img: "https://cdn.myanimelist.net/images/anime/1015/138006.jpg",
    desc: "Perjalanan Elf abadi.",
    studio: "Madhouse",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Journey" }],
    sources: ["Muse Indonesia"]
  },
  {
    id: 11,
    title: "The Eminence in Shadow",
    day: "Rabu",
    time: "22:00",
    genre: ["Action", "Fantasy"],
    img: "https://cdn.myanimelist.net/images/anime/1623/126939.jpg",
    desc: "Cid Kagenou beraksi dalam bayangan.",
    studio: "Nexus",
    episodes: [{ n: 1, ytId: "dQw4w9WgXcQ", title: "Shadow" }],
    sources: ["Bstation"]
  },
  { id: 12, title: "Oregairu S2", day: "Jumat", time: "00:30", genre: ["Romance"], img: "https://cdn.myanimelist.net/images/anime/3/74407.jpg", desc: "Hubungan rumit.", studio: "feel.", episodes: [{n:1, ytId:"p5H97H7fV3w", title:"Changes"}], sources: ["Muse Indonesia"] },
  { id: 13, title: "Oregairu S3", day: "Jumat", time: "01:00", genre: ["Romance"], img: "https://cdn.myanimelist.net/images/anime/1530/108115.jpg", desc: "Akhir SMA.", studio: "feel.", episodes: [{n:1, ytId:"Y_G97H7fV3w", title:"The End"}], sources: ["Muse Indonesia"] },
  { id: 14, title: "Black Clover", day: "Selasa", time: "18:00", genre: ["Magic"], img: "https://cdn.myanimelist.net/images/anime/2/88336.jpg", desc: "Asta sihir.", studio: "Pierrot", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Asta"}], sources: ["Bstation"] },
  { id: 15, title: "My Hero Academia", day: "Sabtu", time: "17:30", genre: ["Hero"], img: "https://cdn.myanimelist.net/images/anime/1911/142363.jpg", desc: "Deku All Might.", studio: "Bones", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Origin"}], sources: ["Ani-One"] },
  { id: 16, title: "Naruto Shippuden", day: "Senin", time: "19:00", genre: ["Ninja"], img: "https://cdn.myanimelist.net/images/anime/1565/111305.jpg", desc: "Kisah Naruto.", studio: "Pierrot", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Home"}], sources: ["Bstation"] },
  { id: 17, title: "Hunter x Hunter", day: "Jumat", time: "20:00", genre: ["Adventure"], img: "https://cdn.myanimelist.net/images/anime/11/33657.jpg", desc: "Gon Hunter.", studio: "Madhouse", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Departure"}], sources: ["Bstation"] },
  { id: 18, title: "Haikyuu!!", day: "Kamis", time: "19:00", genre: ["Sports"], img: "https://cdn.myanimelist.net/images/anime/7/76014.jpg", desc: "Voli Karasuno.", studio: "Production I.G", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Start"}], sources: ["Ani-One"] },
  { id: 19, title: "Tokyo Revengers", day: "Minggu", time: "01:00", genre: ["Action"], img: "https://cdn.myanimelist.net/images/anime/1452/115527.jpg", desc: "Geng motor.", studio: "LIDENFILMS", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Takemichi"}], sources: ["Muse Indonesia"] },
  { id: 20, title: "Oshi no Ko", day: "Rabu", time: "22:00", genre: ["Drama"], img: "https://cdn.myanimelist.net/images/anime/1812/134736.jpg", desc: "Dunia Idol.", studio: "Doga Kobo", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Idol"}], sources: ["Ani-One"] },
  { id: 21, title: "Horimiya", day: "Minggu", time: "21:00", genre: ["Romance"], img: "https://cdn.myanimelist.net/images/anime/1103/112387.jpg", desc: "Cinta rahasia.", studio: "CloverWorks", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Secret"}], sources: ["Bstation"] },
  { id: 22, title: "Lycoris Recoil", day: "Sabtu", time: "22:30", genre: ["Action"], img: "https://cdn.myanimelist.net/images/anime/1244/124503.jpg", desc: "Gadis agen.", studio: "A-1 Pictures", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Lycoris"}], sources: ["Ani-One"] },
  { id: 23, title: "Bleach: TYBW", day: "Sabtu", time: "23:30", genre: ["Action"], img: "https://cdn.myanimelist.net/images/anime/1764/126627.jpg", desc: "Perang Quincy.", studio: "Pierrot", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"War"}], sources: ["Ani-One"] },
  { id: 24, title: "Steins;Gate", day: "Selasa", time: "20:00", genre: ["Sci-Fi"], img: "https://cdn.myanimelist.net/images/anime/15/31355.jpg", desc: "Time travel.", studio: "White Fox", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Future"}], sources: ["Bstation"] },
  { id: 25, title: "Dr. Stone", day: "Kamis", time: "22:00", genre: ["Sci-Fi"], img: "https://cdn.myanimelist.net/images/anime/1613/102179.jpg", desc: "Dunia batu.", studio: "TMS", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Stone"}], sources: ["Ani-One"] },
  { id: 26, title: "Mushoku Tensei", day: "Minggu", time: "22:00", genre: ["Isekai"], img: "https://cdn.myanimelist.net/images/anime/1530/112615.jpg", desc: "Hidup baru Rudy.", studio: "Studio Bind", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Rudy"}], sources: ["Muse Indonesia"] },
  { id: 27, title: "Kaguya-sama", day: "Sabtu", time: "23:00", genre: ["Romance"], img: "https://cdn.myanimelist.net/images/anime/1295/106551.jpg", desc: "War of love.", studio: "A-1 Pictures", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Love"}], sources: ["Bstation"] },
  { id: 28, title: "Mashle", day: "Sabtu", time: "00:00", genre: ["Comedy"], img: "https://cdn.myanimelist.net/images/anime/1638/131438.jpg", desc: "Otot vs Sihir.", studio: "A-1 Pictures", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Magic"}], sources: ["Ani-One"] },
  { id: 29, title: "Blue Box", day: "Kamis", time: "23:56", genre: ["Sports"], img: "https://cdn.myanimelist.net/images/anime/1900/144933.jpg", desc: "Cinta olahraga.", studio: "Telecom", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Box"}], sources: ["Netflix"] },
  { id: 30, title: "Vinland Saga", day: "Senin", time: "00:00", genre: ["Action"], img: "https://cdn.myanimelist.net/images/anime/1500/103005.jpg", desc: "Kisah Viking.", studio: "MAPPA", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Thor"}], sources: ["Netflix"] },
  { id: 31, title: "Bungou Stray Dogs", day: "Rabu", time: "21:00", genre: ["Action"], img: "https://cdn.myanimelist.net/images/anime/1505/135967.jpg", desc: "Detektif super.", studio: "Bones", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"BSD"}], sources: ["Ani-One"] },
  { id: 32, title: "Mob Psycho 100", day: "Kamis", time: "22:00", genre: ["Action"], img: "https://cdn.myanimelist.net/images/anime/1918/127878.jpg", desc: "Psikis Mob.", studio: "Bones", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Mob"}], sources: ["Bstation"] },
  { id: 33, title: "Cyberpunk", day: "Selasa", time: "19:00", genre: ["Sci-Fi"], img: "https://cdn.myanimelist.net/images/anime/1818/126435.jpg", desc: "Edgerunners.", studio: "Trigger", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"David"}], sources: ["Netflix"] },
  { id: 34, title: "Re:Zero", day: "Rabu", time: "21:30", genre: ["Isekai"], img: "https://cdn.myanimelist.net/images/anime/11/79410.jpg", desc: "Subaru mati.", studio: "White Fox", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Zero"}], sources: ["Muse Indonesia"] },
  { id: 35, title: "Slime Isekai", day: "Selasa", time: "23:00", genre: ["Isekai"], img: "https://cdn.myanimelist.net/images/anime/1506/117717.jpg", desc: "Rimuru Slime.", studio: "Eight Bit", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Rimuru"}], sources: ["Muse Indonesia"] },
  { id: 36, title: "Blue Exorcist", day: "Minggu", time: "00:00", genre: ["Action"], img: "https://cdn.myanimelist.net/images/anime/10/75195.jpg", desc: "Anak Satan.", studio: "A-1 Pictures", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Rin"}], sources: ["Ani-One"] },
  { id: 37, title: "Fire Force", day: "Sabtu", time: "01:00", genre: ["Action"], img: "https://cdn.myanimelist.net/images/anime/1410/101851.jpg", desc: "Pemadam api.", studio: "David Production", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Fire"}], sources: ["Bstation"] },
  { id: 38, title: "Attack on Titan", day: "Senin", time: "00:00", genre: ["Action"], img: "https://cdn.myanimelist.net/images/anime/10/47347.jpg", desc: "Eren Titan.", studio: "MAPPA", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Titan"}], sources: ["Ani-One"] },
  { id: 39, title: "Overlord", day: "Selasa", time: "21:00", genre: ["Isekai"], img: "https://cdn.myanimelist.net/images/anime/10/73215.jpg", desc: "Ainz Ooal.", studio: "Madhouse", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"King"}], sources: ["Bstation"] },
  { id: 40, title: "Eighty Six", day: "Minggu", time: "00:00", genre: ["Mecha"], img: "https://cdn.myanimelist.net/images/anime/1987/117507.jpg", desc: "Perang robot.", studio: "A-1 Pictures", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"86"}], sources: ["Bstation"] },
  { id: 41, title: "Your Lie in April", day: "Jumat", time: "20:00", genre: ["Music"], img: "https://cdn.myanimelist.net/images/anime/3/67177.jpg", desc: "Sedih biola.", studio: "A-1 Pictures", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Arima"}], sources: ["Netflix"] },
  { id: 42, title: "Grand Blue", day: "Sabtu", time: "02:00", genre: ["Comedy"], img: "https://cdn.myanimelist.net/images/anime/1160/94273.jpg", desc: "Diving lucu.", studio: "Zero-G", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Beer"}], sources: ["Bstation"] },
  { id: 43, title: "Hell's Paradise", day: "Sabtu", time: "23:00", genre: ["Action"], img: "https://cdn.myanimelist.net/images/anime/1620/134449.jpg", desc: "Pulau maut.", studio: "MAPPA", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Island"}], sources: ["Netflix"] },
  { id: 44, title: "Wind Breaker", day: "Kamis", time: "23:00", genre: ["Action"], img: "https://cdn.myanimelist.net/images/anime/1460/141708.jpg", desc: "Geng sekolah.", studio: "CloverWorks", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Sakura"}], sources: ["Bstation"] },
  { id: 45, title: "Food Wars", day: "Sabtu", time: "20:00", genre: ["Cooking"], img: "https://cdn.myanimelist.net/images/anime/11/74520.jpg", desc: "Soma masak.", studio: "J.C.Staff", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Cook"}], sources: ["Ani-One"] },
  { id: 46, title: "Assassination", day: "Jumat", time: "21:00", genre: ["Comedy"], img: "https://cdn.myanimelist.net/images/anime/8/70857.jpg", desc: "Koro sensei.", studio: "Lerche", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Kill"}], sources: ["Bstation"] },
  { id: 47, title: "Gintama", day: "Senin", time: "18:00", genre: ["Comedy"], img: "https://cdn.myanimelist.net/images/anime/10/73274.jpg", desc: "Koplak.", studio: "Sunrise", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Joke"}], sources: ["Bstation"] },
  { id: 48, title: "Clannad", day: "Sabtu", time: "19:00", genre: ["Drama"], img: "https://cdn.myanimelist.net/images/anime/10/11130.jpg", desc: "Dango sedih.", studio: "KyoAni", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Cry"}], sources: ["Bstation"] },
  { id: 49, title: "SAO", day: "Minggu", time: "22:00", genre: ["Action"], img: "https://cdn.myanimelist.net/images/anime/11/39717.jpg", desc: "Game maut.", studio: "A-1 Pictures", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Game"}], sources: ["Netflix"] },
  { id: 50, title: "Violet Evergarden", day: "Kamis", time: "20:00", genre: ["Drama"], img: "https://cdn.myanimelist.net/images/anime/1795/95088.jpg", desc: "Surat cinta.", studio: "KyoAni", episodes: [{n:1, ytId:"dQw4w9WgXcQ", title:"Violet"}], sources: ["Netflix"] }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = animeDatabase;
}
  {
    id: 7,
    title: "Bleach: Thousand-Year Blood War Part 4",
    day: "Senin",
    time: "22:00",
    genre: ["Action", "Supernatural", "Shounen"],
    img: "https://images.unsplash.com/photo-1611171711912-e458ba951f39?w=400&h=600&fit=crop",
    desc: "Ichigo dan para Soul Reaper menghadapi Yhwach dalam pertempuran pamungkas. True Bankai Ichigo akhirnya terungkap!",
    studio: "Pierrot",
    episodes: [
      { n: 1, ytId: "dQw4w9WgXcQ", title: "The Almighty" },
      { n: 2, ytId: "dQw4w9WgXcQ", title: "Ichigo's True Bankai" },
      { n: 3, ytId: "dQw4w9WgXcQ", title: "The End of Quincy" },
      { n: 4, ytId: "dQw4w9WgXcQ", title: "Epilogue: 10 Years Later" }
    ],
    sources: ["Ani-One", "Bstation"]
  },
  {
    id: 8,
    title: "Spy x Family Season 3",
    day: "Sabtu",
    time: "20:00",
    genre: ["Comedy", "Action", "Slice of Life"],
    img: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=600&fit=crop",
    desc: "Misi keluarga Forger berlanjut! Anya menghadapi ujian Imperial Scholars sementara Loid dan Yor menangani misi rahasia yang saling berkaitan.",
    studio: "Wit Studio & CloverWorks",
    episodes: [
      { n: 1, ytId: "dQw4w9WgXcQ", title: "Operation: Scholar" },
      { n: 2, ytId: "dQw4w9WgXcQ", title: "Yor's Secret Mission" },
      { n: 3, ytId: "dQw4w9WgXcQ", title: "Bond's Vision" },
      { n: 4, ytId: "dQw4w9WgXcQ", title: "Family Vacation Arc" }
    ],
    sources: ["Muse Indonesia", "Ani-One"]
  },
  {
    id: 9,
    title: "Frieren: Beyond Journey's End Season 2",
    day: "Kamis",
    time: "21:30",
    genre: ["Fantasy", "Adventure", "Drama"],
    img: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=400&h=600&fit=crop",
    desc: "Perjalanan Frieren berlanjut ke utara. Misteri tentang masa lalu Hero Himmel dan rahasia tentang elf immortality perlahan terungkap.",
    studio: "Madhouse",
    episodes: [
      { n: 1, ytId: "dQw4w9WgXcQ", title: "The Northern Lands" },
      { n: 2, ytId: "dQw4w9WgXcQ", title: "Himmel's Legacy" },
      { n: 3, ytId: "dQw4w9WgXcQ", title: "The Elf Who Understands Time" },
      { n: 4, ytId: "dQw4w9WgXcQ", title: "Magic of the Ancient Era" }
    ],
    sources: ["Muse Indonesia", "Bstation"]
  },
  {
    id: 10,
    title: "Blue Lock Season 3",
    day: "Minggu",
    time: "23:00",
    genre: ["Sports", "Drama", "Psychological"],
    img: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=600&fit=crop",
    desc: "U-20 World Cup dimulai! Isagi Yoichi memimpin tim Jepang dengan egoisme barunya melawan striker terbaik dunia dalam turnamen yang menentukan segalanya.",
    studio: "8bit",
    episodes: [
      { n: 1, ytId: "dQw4w9WgXcQ", title: "World Stage" },
      { n: 2, ytId: "dQw4w9WgXcQ", title: "Isagi's Evolution" },
      { n: 3, ytId: "dQw4w9WgXcQ", title: "The Egoist's Goal" },
      { n: 4, ytId: "dQw4w9WgXcQ", title: "World Class Striker" }
    ],
    sources: ["Ani-One", "Bstation"]
  }
];

// Export untuk digunakan di file lain
if (typeof module !== 'undefined' && module.exports) {
  module.exports = animeDatabase;
}
